name: Create Release

on:
  workflow_dispatch

jobs:
  create-release:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Define next taf
        id: tag
        run: |
          latest_tag=$(git tag -l --sort=-v:refname | head -1)
          IFS='.' read -r -a parts <<< "${latest_tag#v}"
          major="${parts[0]}"
          minor="${parts[1]}"
          patch="${parts[2]}"
          new_tag="v$major.$minor.$((patch + 1))"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Build
        run: echo ${{ github.sha }} > Release.txt

      - name: Test
        run: cat Release.txt

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.new_tag}}
          name: ${{ steps.tag.outputs.new_tag}}
          files: Release.txt
        env:
          GITHUB_TOKEN:
